services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "80:80"    # Tráfico HTTP (Local/Redirección)
      - "443:443"  # Tráfico HTTPS (Azure)
    volumes:
      - ./gateway/certs:/etc/nginx/certs:ro # Para los certificados en Azure
    depends_on:
      - users
      - webapp
      - gamey
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es4a-users:latest
    # ports: - "3000:3000" <-- ELIMINADO: Ya no se accede directamente
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        # La API ahora se accede a través de la ruta relativa del Gateway
        - VITE_API_URL=/api/users 
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es4a-webapp:latest
    # ports: - "80:80" <-- ELIMINADO: Nginx servirá la web
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es4a-gamey:latest
    # ports: - "4000:4000" <-- ELIMINADO
    networks:
      - monitor-net
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
